---
# tasks file for loadbalancerrole
- name: "configure yum "
  yum_repository:
            name: dvd1
            description: appstream
            baseurl: file:///run/media/root/RHEL-8-0-0-BaseOS-x86_64/AppStream
            file: rehel
            gpgcheck: no
- name: "configure yum"
  yum_repository:
            name: dvd2
            description: baseos
            baseurl: file:///run/media/root/RHEL-8-0-0-BaseOS-x86_64/BaseOS
            file: rehel
            gpgcheck: no
- name: "install haproxy"
  package:
       name: "haproxy"
       state: present

- name: "configur /etc/haproxy/haproxy.cfg file"
  template:
       dest: "/etc/haproxy/haproxy.cfg"
       src: "haproxy.cfg.j2"
  notify:
  - Restart haproxy

- name: "start haproxy services"
  service:
       name: "haproxy"
       state: started


